### ISSUE TITLE
conceptual model with diagram.drawio app

### ISSUE THREAD

**Issue by AditiBista** [CWWhitney/nepal_turmeric#1]
![turmeric_ Diagram drawio](https://github.com/CWWhitney/nepal_turmeric/assets/138200101/0f8e9df6-925b-433f-b41c-7fb225cf0f9e)

**Comment by CWWhitney** [comment]
We have a model that more-or-less reflects the case ... @PrajnaKARai can you offer feedback here? 

What we probably need is the R script that backs this up. @AditiBista I suggest that you please make a simple model of the farm-level decision of turmeric or baseline (cereal crops are the alternative?) and build the R script to reflect what is shown there. This will help to build upon it step by step. 

![Screenshot 2023-12-05 at 14 55 19](https://github.com/CWWhitney/nepal_turmeric/assets/19190662/6b65f698-96ed-4154-8546-1f0b2f129618)

**Comment by AditiBista** [comment]
thank you so much for your feedback.

**Comment by PrajnaKARai** [comment]
@AditiBista please include the effects of extreme climate events on turmeric production. Also, the disease/pest should go to turmeric production. There's no need to have a separate risk bubble if you are not talking about post-harvest disease/pest or extreme event effects. Similarly, for cereal production and related risks.

**Comment by AditiBista** [comment]
@PrajnaKARai @CWWhitney . Thanks for the suggestion. This is the modified model . Is it ok?
![Updated Diagram drawio](https://github.com/CWWhitney/nepal_turmeric/assets/138200101/1040f008-a94b-4ae7-959e-12bca8947e42)

**Comment by PrajnaKARai** [comment]
yeah
